# Permalinks
permalink:           pretty

# Setup
title:               SpeechConvergence
tagline:             HCI
url:                 https://sankar-mukherjee.github.io/SpeechConvergence/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Sankar Mukherjee
  url:               https://sankar-mukherjee.github.io/
  email:             sankar1535@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/sankar-mukherjee/SpeechConvergence

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
